### PR TITLE
Added travis ci support to ensure coverage

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by amilajack** [comment]
@henryboldi Please enable these tests. They're useful for PRs

**Comment by amilajack** [comment]
Also I am willing to offer long term support and serve as a contributor for this project, if its fine with you.

**Comment by daveloyall** [comment]
Consider this as well, please: https://github.com/brbsix/felony/commit/aa1b4b37bbc57cede6ccc6bd64b0055e80754928

**Comment by TechyPeople** [comment]
Travis CI will be implemented in the near future.  Updates will be posted in #72.

**Pull request closed without merging**
