### PR TITLE
add import key option to UI

### PR DESCRIPTION
**Pull request by greg-js**
This is a possible, straightforward approach to add existing private keys as discussed in #54 #34 and #7 

There are other potential approaches though which may be incompatible with this one but there seemed to be some interest in it so I decided to submit this as a PR. Up to you to decide what to do with it ;)

You might want to test it some more first, but it _should_ just add and save the keys in exactly the same way as when they're generated.

### CODE REVIEW

**Comment by henryboldi** [comment]
Thanks so much Greg! Can you add screenshots to this PR?

**Comment by greg-js** [comment]
Sure, I'm away from my dev machine now but I'll upload some tonight :)

**Comment by greg-js** [comment]
Uploaded two screenshots and a linux and mac build [here](https://github.com/greg-js/felony/releases/tag/0.10.3-importkey). Don't mind the description and date there, that's just because I edited an existing release instead of making a new one :)

**Comment by henryboldi** [comment]
The code looks good, but I fear the additions to the UI will be too confusing. I will make some designs when I get a chance and merge it with your code. How does that sound?

**Comment by greg-js** [comment]
Sounds good to me. And I think you're right about the UI, there's definitely a better way to do this.

**Comment by frankcash** [comment]
Working on testing this locally!  
screen shot 2016-08-16 at 11 03 42 pm

**Comment by frankcash** [comment]
This view could do with some improving
screen shot 2016-08-16 at 11 53 00 pm

**Comment by casesandberg** [comment]
Is there any blockers on this or is it still being worked on?

**Comment by frankcash** [comment]
This could be merged, I'd just like if the UI problem that I mentioned was fixed.

**Comment by greg-js** [comment]
I actually agree that it could be implemented in a better-looking way, especially considering this app looks so nice as it is. I'm really not a designer though, not sure if I can come up with a better look..

**Comment by frankcash** [comment]
I'm not either, but we could have a flow of initial screen when user has no key

Options to generate key or import key, and then goes to a specific UI for each.

**Comment by greg-js** [comment]
How about something a little more like this? It's missing some polish and animation jazz but you're right I like the splash screen much better too, compared to switching the buttons over.

gifrecord_2016-09-23_180706

**Comment by greg-js** [comment]
Oops, I was playing with a mobile app yesterday and must have accidentally closed this, my bad.

**Comment by Tasemu** [comment]
Any word on this?

**Pull request closed without merging**
